public class ForPracticeClassDemo {
    public static void methodPractice(){
        //Job_Shubham__c jobObject=[select Id,CreatedDate,Name from Job_Shubham__c where Id='a042w00000yHyBYAA0'];
        // Candidate_Shubham__c candiObject=[SELECT Id, Name, First_Name__c, Last_Name__c, CreatedDate, Application_Date__c FROM Candidate_Shubham__c where Id='a052w00000ExQu8AAF'];
        // DateTime createdDateTime = candiObject.CreatedDate;
        // String createdDateString = createdDateTime.format('yyyy-MM-dd');
        // candiObject.Application_Date__c = Date.valueOf(createdDateString);
        // System.debug(candiObject.Application_Date__c);

    }
}