public class HandlerForLeadTrigger {
    //public static void forAvoidEmailLastNameDateDuplication(List<Lead> leadObjectList){

        //for(Lead leadObject:leadObjectList){
           // List<Lead> oldLeadList=[select CreatedDate,Id, LastName, Email from Lead ];
			//where (LastName=:leadObject.LastName And CreatedDate=:leadObject.CreatedDate) OR (Email=:leadObject.Email And CreatedDate=:leadObject.CreatedDate)
            //System.debug(oldLeadList+'pppppppppppppppppppp');
               // for(Lead objectLead:oldLeadList){
                    //Date oldDate=date.newInstance(objectLead.CreatedDate.year(), objectLead.CreatedDate.month(), objectLead.CreatedDate.day());
                    //Date newDate=date.newInstance(leadObject.CreatedDate.year(), leadObject.CreatedDate.month(), leadObject.CreatedDate.day());
                    //if(objectLead.LastName == leadObject.LastName && objectLead.Email == leadObject.Email /*&& oldDate == newDate */){
                        //leadObject.Id.addError(Label.errorMessage);
                     //   leadObject.Id.addError('This User is Already Exist');
                    //}
                   // else if(objectLead.Email == leadObject.Email /*&& oldDate == newDate */ ){
                    //    leadObject.Email.addError('This Email is Already in use for lead ');
                   // }
                   // else if(objectLead.LastName == leadObject.LastName /*&& oldDate == newDate */){
                     //   leadObject.LastName.addError('This Last Name is Already Exist ');
                   // }
                //}
            
//        }
//    }
}